// Template: Models (ApiModel.t4) version 5.0

// This code was generated by AMF Server Scaffolder

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace RAMLTransformation.APIDefinition.Models
{
    public partial class SuccessfulResponse
    {
        

        [Required]
        [MaxLength(0)]
        [MinLength(0)]
		[JsonProperty("location")]
        public string Location { get; set; }

        [Required]
        [MaxLength(0)]
        [MinLength(0)]
		[JsonProperty("vaccine_type")]
        public string Vaccine_type { get; set; }

        [Required]
        [MaxLength(0)]
        [MinLength(0)]
		[JsonProperty("date")]
        public string Date { get; set; }

        [Required]
        [MaxLength(0)]
        [MinLength(0)]
		[JsonProperty("access_token")]
        public string Access_token { get; set; }

        [Required]
        [MaxLength(0)]
        [MinLength(0)]
		[JsonProperty("fullName")]
        public string FullName { get; set; }

        [Required]
        [MaxLength(0)]
        [MinLength(0)]
		[JsonProperty("purpose")]
        public string Purpose { get; set; }

        [MaxLength(0)]
        [MinLength(0)]
		[JsonProperty("symptoms")]
        public string Symptoms { get; set; }
    } // end class

} // end Models namespace

