// Template: Models (ApiModel.t4) version 5.0

// This code was generated by AMF Server Scaffolder

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace RAMLTransformation.APIDefinition.Models
{
    public partial class VaccinestatsVaccinatedLocationGet200
    {
        
    } // end class

} // end Models namespace

